// Code generated by mockery v1.0.0. DO NOT EDIT.

package hub

import criers "github.com/sgettys/bellman/pkg/criers"
import mock "github.com/stretchr/testify/mock"

// MockReceiverRegistry is an autogenerated mock type for the ReceiverRegistry type
type MockReceiverRegistry struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockReceiverRegistry) Close() {
	_m.Called()
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *MockReceiverRegistry) Register(_a0 string, _a1 criers.Crier) {
	_m.Called(_a0, _a1)
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *MockReceiverRegistry) Send(_a0 string, _a1 []byte) {
	_m.Called(_a0, _a1)
}

// SendAll provides a mock function with given fields: _a0
func (_m *MockReceiverRegistry) SendAll(_a0 []byte) {
	_m.Called(_a0)
}
